[package]
name = "mushroom-tracker"
version = "1.0.2"
description = "Chaotic Neutral Mycology — Desktop"
authors = ["You"]
edition = "2021"

[[bin]]
name = "mushroom-tracker"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
