// tests/e2e/helpers/testData.ts
export const e2eData = {
  strainLibrary: {
    type: "Spore Syringe",
    strainName: "E2E Golden Teacher",
    scientificName: "Psilocybe cubensis",
    quantity: "10",
    unit: "ml",
    acquired: "2026-03-01",
  },
  supplies: [
    {
      name: "E2E Agar Cups",
      cost: "20",
      quantity: "20",
      unit: "count",
      type: "container",
    },
    {
      name: "E2E Grain",
      cost: "30",
      quantity: "5000",
      unit: "g",
      type: "substrate",
    },
    {
      name: "E2E Bulk Substrate",
      cost: "40",
      quantity: "10000",
      unit: "g",
      type: "substrate",
    },
    {
      name: "E2E Capsule Shells",
      cost: "0.05",
      quantity: "500",
      unit: "count",
      type: "packaging",
    },
  ],
  recipes: [
    {
      name: "E2E Agar Recipe",
      tags: "e2e,agar",
      servingLabel: "plates",
      yield: "1",
      ingredient: {
        supplyName: "E2E Agar Cups",
        amount: "1",
        unit: "count",
      },
      instructions: "Generic agar prep for Playwright validation.",
    },
    {
      name: "E2E Grain Recipe",
      tags: "e2e,grain",
      servingLabel: "jars",
      yield: "1",
      ingredient: {
        supplyName: "E2E Grain",
        amount: "500",
        unit: "g",
      },
      instructions: "Generic grain prep for Playwright validation.",
    },
    {
      name: "E2E Bulk Recipe",
      tags: "e2e,bulk",
      servingLabel: "tubs",
      yield: "1",
      ingredient: {
        supplyName: "E2E Bulk Substrate",
        amount: "3000",
        unit: "g",
      },
      instructions: "Generic bulk prep for Playwright validation.",
    },
    {
      name: "E2E Capsule Recipe",
      tags: "e2e,capsule,post",
      scope: "post-production",
      servingLabel: "capsules",
      yield: "100",
      ingredient: {
        supplyName: "E2E Capsule Shells",
        amount: "100",
        unit: "count",
      },
      instructions: "Generic capsule assembly for Playwright validation.",
    },
  ],
  grows: {
    agar: {
      type: "Agar",
      created: "2026-03-02",
      initialVolume: "10",
      initialUnit: "ml",
      recipe: "E2E Agar Recipe",
    },
    grain: {
      type: "Grain Jar",
      created: "2026-03-04",
      parentConsume: "5",
      initialVolume: "500",
      initialUnit: "g",
      recipe: "E2E Grain Recipe",
    },
    bulk: {
      type: "Bulk",
      created: "2026-03-06",
      parentConsume: "500",
      bulkVolume: "3000",
      bulkUnit: "g",
      recipe: "E2E Bulk Recipe",
    },
  },
  flushes: [
    { date: "2026-03-10", wet: "120", dry: "12", note: "Flush 1" },
    { date: "2026-03-13", wet: "140", dry: "14", note: "Flush 2" },
    { date: "2026-03-16", wet: "160", dry: "16", note: "Flush 3" },
    { date: "2026-03-19", wet: "180", dry: "18", note: "Flush 4" },
  ],
  totals: {
    wet: "600",
    dry: "60",
  },
  postProcess: {
    extraction: {
      batchName: "E2E Dual Extract Batch",
      extractionType: "dual",
      consumeDry: "30",
      date: "2026-03-20",
      status: "completed",
      outputAmount: "30",
      outputUnit: "mL",
      outputYieldPercent: "50",
      method: "Generic dual extraction for Playwright validation.",
      notes: "Immediate extract lot output for end-to-end coverage.",
      outputLotName: "E2E Dual Extract Batch Output",
    },
    production: {
      batchName: "E2E Capsule Run",
      productType: "capsule",
      consumeSource: "30",
      date: "2026-03-21",
      status: "completed",
      outputCount: "100",
      mgPerUnit: "250",
      variant: "250 mg capsules",
      recipe: "E2E Capsule Recipe",
      packagingCost: "5",
      laborCost: "10",
      overheadCost: "2",
      otherCost: "0",
      pricePerUnit: "2.50",
      msrpPerUnit: "3.00",
      method: "Generic encapsulation run for Playwright validation.",
      notes: "Creates finished inventory directly from extract lot.",
      outputLotName: "E2E Capsule Run Output",
    },
    sale: {
      quantity: "12",
      unitPrice: "2.50",
      date: "2026-03-22",
      destinationType: "customer",
      destinationName: "E2E Test Customer",
      destinationLocation: "Playwright Clinic",
      reason: "E2E validation sale",
      note: "Sold during Playwright finished-inventory validation.",
      revenue: "30.00",
      remainingAfterSale: "88",
    },
  },
};