// src/utils/tourSteps.js
/**
 * Steps map: routeKey -> array of steps.
 * If selector is present and found, it gets a spotlight; otherwise the tooltip
 * stays usable in the center of the screen.
 *
 * Bump TOUR_VERSION whenever tour copy, ordering, or behavior changes so each
 * page can be shown once again for the new guide version.
 */
export const TOUR_VERSION = 4;
export const TOUR_CONTROL_EVENT = "cnm:tour-control";

const steps = {
  dashboard: [
    {
      title: "Dashboard overview",
      body: "This is the daily cultivation view. See active records, current type and stage counts, cost summaries, and the grows that need attention.",
    },
    {
      title: "Create a cultivation record",
      body: "Start an Agar, LC, Grain Jar, Bulk, or Other record with the current grow form.",
      selector: '[data-tour="new-grow"]',
    },
    {
      title: "Stage overview",
      body: "These chips summarize how many active records are in each stage. They are counts, not filters.",
      selector: '[data-tour="stage-filters"]',
    },
    {
      title: "Quick actions",
      body: "Use the floating action button to start a grow, open a status logger, or prepare a photo upload.",
      selector: '[data-tour="quick-actions"]',
    },
    {
      title: "Scan a record",
      body: "Use Scan to open a supported barcode or QR-linked record.",
      selector: '[data-tour="scan"]',
    },
  ],

  tasks: [
    {
      title: "Tasks and SOP follow-ups",
      body: "Manage manual tasks and tasks generated from SOP workflows. Due dates, completion, recurrence, reminders, and grow links stay attached to each task.",
      selector: '[data-tour="tasks-root"]',
    },
    {
      title: "Filter the task list",
      body: "Show all tasks, general tasks, grow-linked tasks, completed work, or selected tags.",
      selector: '[data-tour="task-filters"]',
    },
    {
      title: "Quick add",
      body: "Create a task from one line, including natural-language timing, priority, tags, recurrence, and reminder lead time.",
      selector: '[data-tour="task-quick-add"]',
    },
  ],

  analytics: [
    {
      title: "Analytics Command Center",
      body: "Review cultivation, production, inventory, sales, quality, and supply reports without losing historical records.",
    },
    {
      title: "Choose a workspace",
      body: "Switch between focused analytics workspaces. Each workspace contains the reports relevant to that part of the operation.",
      selector: '[data-tour="analytics-workspaces"]',
    },
    {
      title: "Filter the report data",
      body: "Use date, strain, active-versus-history, grouping, and chart-value controls when they apply to the selected workspace.",
      selector: '[data-tour="analytics-filters"]',
    },
    {
      title: "Export analytics",
      body: "Export the current analytics data as CSV or JSON when your plan includes exports. Full account backups remain under Settings → Data.",
      selector: '[data-tour="analytics-export"]',
    },
  ],

  calendar: [
    {
      title: "Calendar",
      body: "The calendar combines grow milestones with real task due dates. Tasks without due dates remain in Tasks instead of being placed on an unrelated date.",
    },
    {
      title: "Filter the calendar",
      body: "Show or hide grow milestones, open tasks, completed tasks, manual tasks, and tasks generated by SOP workflows.",
      selector: '[data-tour="calendar-filters"]',
    },
    {
      title: "Use the calendar as a navigator",
      body: "Open a task from the calendar to continue it in Tasks. Grow milestones keep cultivation timing visible alongside scheduled work.",
    },
  ],

  timeline: [
    {
      title: "Grow timeline",
      body: "Use Timeline when you want chronological context instead of the dashboard's current-state view.",
    },
    {
      title: "Follow stage history",
      body: "Review stage changes across cultivation records so you can see how each grow progressed over time.",
    },
    {
      title: "Keep documentation in context",
      body: "Notes and stage photos stay part of the grow history, helping you compare what happened around each stage transition.",
    },
  ],

  postprocess: [
    {
      title: "Post Processing",
      body: "Follow harvested material through dry lots, extraction, manufacturing, finished inventory, sales, and retained history.",
    },
    {
      title: "Workflow sections",
      body: "Use these sections to move between active material, production work, finished inventory, outbound sales, and historical records.",
      selector: '[data-tour="postprocess-tabs"]',
    },
    {
      title: "Keep the chain traceable",
      body: "Post-processing records are designed to preserve the relationship between source material, production work, package runs, inventory, and final disposition.",
    },
  ],

  cog: [
    {
      title: "Cost of Goods",
      body: "Use COG to maintain the supplies and costs that feed recipes, SOP runs, grow estimates, and analytics.",
      selector: '[data-tour="cog-root"]',
    },
    {
      title: "Keep costs current",
      body: "Accurate supply costs make downstream recipe, grow, and production estimates more useful.",
    },
  ],

  recipes: [
    {
      title: "Recipes and SOP workflows",
      body: "Use Recipes to keep repeatable process instructions and recipe versions in one place.",
    },
    {
      title: "Start traceable work",
      body: "Eligible SOP workflows can start new grows from approved templates instead of re-entering the same setup each time.",
    },
    {
      title: "Carry the workflow forward",
      body: "When an SOP includes generated tasks, the follow-up work stays connected to the process instead of living in a separate checklist.",
    },
  ],

  strains: [
    {
      title: "Strains and culture library",
      body: "Keep strain identity, aliases, images, notes, stored culture records, and linked grow history together.",
    },
    {
      title: "Separate identity from individual grows",
      body: "A strain record is the reusable library entry; cultivation records track the individual grow work created from it.",
    },
    {
      title: "Use the library for continuity",
      body: "Stored culture information and linked grow history make it easier to trace what material you still have and where it has been used.",
    },
  ],

  labels: [
    {
      title: "Packaging labels",
      body: "Use Labels to preview and print from current product, package/SKU, strain, and batch data.",
    },
    {
      title: "Labels follow tracked data",
      body: "Verify the underlying batch and package information before printing so the label stays consistent with the records in the app.",
    },
    {
      title: "Label defaults live in Settings",
      body: "Printing happens here; reusable label defaults and presentation options remain under Settings → Labels.",
    },
  ],

  archive: [
    {
      title: "Archive and history",
      body: "Archive keeps completed, contaminated, consumed, depleted, or otherwise historical records available without crowding active work.",
    },
    {
      title: "Traceability stays intact",
      body: "Historical grow and post-processing records remain available for review instead of being treated like disposable data.",
    },
  ],

  admin: [
    {
      title: "Private administration",
      body: "The Admin workspace is available only to trusted internal administrator accounts and uses backend-authorized account data.",
    },
    {
      title: "Account status",
      body: "Review effective access, base billing, email verification, and explicit marketing consent as separate account states.",
    },
    {
      title: "Promotional access",
      body: "Administrative promotions can add temporary access without replacing Stripe as the authority for purchased subscriptions.",
    },
  ],

  settings: [
    {
      title: "Account and sync",
      body: "Start here for account identity, email verification, device unlock, and communication preferences.",
    },
    {
      title: "Appearance",
      body: "Choose the display mode, theme style, and accent used by the application.",
      selector: '[data-tour="theme-style"]',
    },
    {
      title: "Accent color",
      body: "Change the interface accent without changing the Chaotic background artwork.",
      selector: '[data-tour="accent-color"]',
    },
    {
      title: "Guided tours",
      body: "Turn page guides on or off, replay this page, or reset all page tours from this control.",
      selector: '[data-tour="guide-controls"]',
    },
    {
      title: "Reminders",
      body: "Configure task reminders, grow-stage reminders, browser permission, reminder time, and stage windows.",
      selector: '[data-tour="reminders-block"]',
    },
    {
      title: "Subscription, labels, and data",
      body: "The remaining Settings tabs contain subscription management, label defaults, backup and restore, storage information, and advanced controls.",
    },
  ],
};

export default steps;
