name: Web Release

on:
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      # Compute "/<repo-name>/" at runtime so you don't hardcode it
      - name: Compute base path
        run: echo "BASE=/${GITHUB_REPOSITORY#*/}/" >> "$GITHUB_ENV"

      - name: Build (with correct base for GitHub Pages)
        run: npm run build -- --base "$BASE"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        name: Deploy to Pages
        uses: actions/deploy-pages@v4
